### ISSUE TITLE
跨分区rename Error: EXDEV: cross-device link not permitted

### ISSUE THREAD

**Issue by lemontree2000** [yeyan1996/file-upload#1]
系统： window10
浏览器： chrome 79

跨分区rename 时会出现权限问题，导致不能生成新的文件从而接口一直pending
![Snipaste_2020-01-13_16-33-51](https://user-images.githubusercontent.com/21957062/72241930-1dcdc000-3623-11ea-8525-ccbbe1e80848.png)

![Snipaste_2020-01-13_16-34-57](https://user-images.githubusercontent.com/21957062/72241943-22927400-3623-11ea-9e1e-3384a6fa948c.png)

**Comment by zzzzzhowie** [comment]
已修复，fx-extra 的 rename 方法 windows 平台似乎有权限的问题，换成 fse.move 了
