### ISSUE TITLE
multiparty解析后的fields和file都是undefined

### ISSUE THREAD

**Issue by q774221810** [yeyan1996/file-upload#15]
multiparty解析后的fields和file都是undefined

**Comment by nicholasfung68** [comment]
兄弟解决了吗？我这也遇到了，除此之外我自己跟着敲代码跑起来，有遇到过合并请求已经发送到服务端，但是文件操作还没结束，报错说无法删除非空文件夹，也有说不存在路径或者文件的……

**Comment by nicholasfung68** [comment]
这个解决了，之前我用的是node v14版本，我在网上搜了一下，也有其他人遇到了这个问题，我把node版本换成v8版本就没问题了

**Comment by lgCode** [comment]
> 这个解决了，我用的是node v14版本，我在网上搜了一下，也有其他人遇到了这个问题，我把node版本换成v8版本之前把问题了

兄弟，我node换成V8.12.0，现在报错：node_modules\universalify\index.js 报错15行；fn.name的name为undefined，我切换成V10版本就没这个错，但是files为undefined。

**Comment by nicholasfung68** [comment]
我用的是node v8.17.0，切换node版本后删除node_modules重新安装依赖，跑起来没问题

**Comment by lgCode** [comment]
我也用8.17.0试过了，一样报错，头蒙蒙的，哈哈哈

**Comment by PossibleMaybe** [comment]
亲测有效，把node版本切到v8.17.0，然后删除node_modules重新安装，不报错了

**Comment by zzzzzhowie** [comment]
已经修复
