### ISSUE TITLE
merge请求的发出时机

### ISSUE THREAD

**Issue by sunnyabc789** [yeyan1996/file-upload#3]
当chunk数量小于6条时
你会发现
merge请求是和chunk的上传请求一起发出去的
不是代码设计思想那样的 等chunk上传完毕 发一条merge

这会有什么问题呢？
此时的merge请求到了node端 fs.readdir(PATH) 无法读到PATH

为什么是6条呢？
浏览器中 http请求 同一个源一次最多6条 所以小于6条时 merge请求会和chunk上传请求一起发出

**Comment by HHeLiBeB-C** [comment]
确实
