### ISSUE TITLE
提一个问题，掘金问题太多，怕被埋

### ISSUE THREAD

**Issue by webgzh907247189** [yeyan1996/file-upload#5]
关于web worker 那段代码，因为我看lz写的是《另外考虑到如果上传一个超大文件，读取文件内容计算 hash 是非常耗费时间的，并且会引起 UI 的阻塞，导致页面假死状态，所以我们使用 web-worker 在 worker 线程计算 hash》 这个地方我看虽然是webwork在计算hash值，但是一直在等这个值，因为下面要用到这个值。。这个地方不用webworker 是不是一样的呢。反正就算用了，主线程也要等。

**Comment by zzzzzhowie** [comment]
一个很关键的区别在于，web-worker 不会让页面卡死，这个是非常重要的，这就好比为什么废除同步的 ajax 请求

如果页面卡死，是不能执行任何操作的，而使用 web-worker 你可以加个进度条告诉用户正在计算 hash
